/*
 * SPDX-FileCopyrightText: 2026 Zextras <https://www.zextras.com>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> =
	| T
	| { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/* eslint-disable camelcase,no-shadow */
// THIS FILE IS AUTOGENERATED BY GRAPHQL-CODEGEN. DO NOT EDIT!
import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

import type * as Types from './types';

export type TaskFragment = {
	id: string;
	description: string | null;
	priority: Types.Priority;
	reminderAllDay: boolean | null;
	status: Types.Status;
	reminderAt: number | null;
	title: string;
	createdAt: number;
};

export type CreateTaskMutationVariables = Exact<{
	newTask: Types.NewTaskInput;
}>;

export type CreateTaskMutation = {
	createTask: {
		id: string;
		description: string | null;
		priority: Types.Priority;
		reminderAllDay: boolean | null;
		status: Types.Status;
		reminderAt: number | null;
		title: string;
		createdAt: number;
	} | null;
};

export type TrashTaskMutationVariables = Exact<{
	taskId: string;
}>;

export type TrashTaskMutation = { trashTask: string | null };

export type UpdateTaskMutationVariables = Exact<{
	updateTask: Types.UpdateTaskInput;
}>;

export type UpdateTaskMutation = {
	updateTask: {
		id: string;
		description: string | null;
		priority: Types.Priority;
		reminderAllDay: boolean | null;
		status: Types.Status;
		reminderAt: number | null;
		title: string;
		createdAt: number;
	} | null;
};

export type UpdateTaskStatusMutationVariables = Exact<{
	id: string;
	status: Types.Status;
}>;

export type UpdateTaskStatusMutation = { updateTask: { id: string; status: Types.Status } | null };

export type FindTasksQueryVariables = Exact<{
	priority?: Types.Priority | null | undefined;
	status?: Types.Status | null | undefined;
}>;

export type FindTasksQuery = {
	findTasks: Array<{
		id: string;
		priority: Types.Priority;
		createdAt: number;
		reminderAllDay: boolean | null;
		status: Types.Status;
		reminderAt: number | null;
		title: string;
	} | null>;
};

export type GetTaskQueryVariables = Exact<{
	taskId: string;
}>;

export type GetTaskQuery = {
	getTask: {
		id: string;
		priority: Types.Priority;
		createdAt: number;
		description: string | null;
		reminderAllDay: boolean | null;
		status: Types.Status;
		reminderAt: number | null;
		title: string;
	} | null;
};

export const TaskFragmentDoc = {
	kind: 'Document',
	definitions: [
		{
			kind: 'FragmentDefinition',
			name: { kind: 'Name', value: 'Task' },
			typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'Task' } },
			selectionSet: {
				kind: 'SelectionSet',
				selections: [
					{ kind: 'Field', name: { kind: 'Name', value: 'id' } },
					{ kind: 'Field', name: { kind: 'Name', value: 'description' } },
					{ kind: 'Field', name: { kind: 'Name', value: 'priority' } },
					{ kind: 'Field', name: { kind: 'Name', value: 'reminderAllDay' } },
					{ kind: 'Field', name: { kind: 'Name', value: 'status' } },
					{ kind: 'Field', name: { kind: 'Name', value: 'reminderAt' } },
					{ kind: 'Field', name: { kind: 'Name', value: 'title' } },
					{ kind: 'Field', name: { kind: 'Name', value: 'createdAt' } }
				]
			}
		}
	]
} as unknown as DocumentNode<TaskFragment, unknown>;
export const CreateTaskDocument = {
	kind: 'Document',
	definitions: [
		{
			kind: 'OperationDefinition',
			operation: 'mutation',
			name: { kind: 'Name', value: 'createTask' },
			variableDefinitions: [
				{
					kind: 'VariableDefinition',
					variable: { kind: 'Variable', name: { kind: 'Name', value: 'newTask' } },
					type: {
						kind: 'NonNullType',
						type: { kind: 'NamedType', name: { kind: 'Name', value: 'NewTaskInput' } }
					}
				}
			],
			selectionSet: {
				kind: 'SelectionSet',
				selections: [
					{
						kind: 'Field',
						name: { kind: 'Name', value: 'createTask' },
						arguments: [
							{
								kind: 'Argument',
								name: { kind: 'Name', value: 'newTask' },
								value: { kind: 'Variable', name: { kind: 'Name', value: 'newTask' } }
							}
						],
						selectionSet: {
							kind: 'SelectionSet',
							selections: [{ kind: 'FragmentSpread', name: { kind: 'Name', value: 'Task' } }]
						}
					}
				]
			}
		},
		{
			kind: 'FragmentDefinition',
			name: { kind: 'Name', value: 'Task' },
			typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'Task' } },
			selectionSet: {
				kind: 'SelectionSet',
				selections: [
					{ kind: 'Field', name: { kind: 'Name', value: 'id' } },
					{ kind: 'Field', name: { kind: 'Name', value: 'description' } },
					{ kind: 'Field', name: { kind: 'Name', value: 'priority' } },
					{ kind: 'Field', name: { kind: 'Name', value: 'reminderAllDay' } },
					{ kind: 'Field', name: { kind: 'Name', value: 'status' } },
					{ kind: 'Field', name: { kind: 'Name', value: 'reminderAt' } },
					{ kind: 'Field', name: { kind: 'Name', value: 'title' } },
					{ kind: 'Field', name: { kind: 'Name', value: 'createdAt' } }
				]
			}
		}
	]
} as unknown as DocumentNode<CreateTaskMutation, CreateTaskMutationVariables>;
export const TrashTaskDocument = {
	kind: 'Document',
	definitions: [
		{
			kind: 'OperationDefinition',
			operation: 'mutation',
			name: { kind: 'Name', value: 'trashTask' },
			variableDefinitions: [
				{
					kind: 'VariableDefinition',
					variable: { kind: 'Variable', name: { kind: 'Name', value: 'taskId' } },
					type: {
						kind: 'NonNullType',
						type: { kind: 'NamedType', name: { kind: 'Name', value: 'ID' } }
					}
				}
			],
			selectionSet: {
				kind: 'SelectionSet',
				selections: [
					{
						kind: 'Field',
						name: { kind: 'Name', value: 'trashTask' },
						arguments: [
							{
								kind: 'Argument',
								name: { kind: 'Name', value: 'taskId' },
								value: { kind: 'Variable', name: { kind: 'Name', value: 'taskId' } }
							}
						]
					}
				]
			}
		}
	]
} as unknown as DocumentNode<TrashTaskMutation, TrashTaskMutationVariables>;
export const UpdateTaskDocument = {
	kind: 'Document',
	definitions: [
		{
			kind: 'OperationDefinition',
			operation: 'mutation',
			name: { kind: 'Name', value: 'updateTask' },
			variableDefinitions: [
				{
					kind: 'VariableDefinition',
					variable: { kind: 'Variable', name: { kind: 'Name', value: 'updateTask' } },
					type: {
						kind: 'NonNullType',
						type: { kind: 'NamedType', name: { kind: 'Name', value: 'UpdateTaskInput' } }
					}
				}
			],
			selectionSet: {
				kind: 'SelectionSet',
				selections: [
					{
						kind: 'Field',
						name: { kind: 'Name', value: 'updateTask' },
						arguments: [
							{
								kind: 'Argument',
								name: { kind: 'Name', value: 'updateTask' },
								value: { kind: 'Variable', name: { kind: 'Name', value: 'updateTask' } }
							}
						],
						selectionSet: {
							kind: 'SelectionSet',
							selections: [{ kind: 'FragmentSpread', name: { kind: 'Name', value: 'Task' } }]
						}
					}
				]
			}
		},
		{
			kind: 'FragmentDefinition',
			name: { kind: 'Name', value: 'Task' },
			typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'Task' } },
			selectionSet: {
				kind: 'SelectionSet',
				selections: [
					{ kind: 'Field', name: { kind: 'Name', value: 'id' } },
					{ kind: 'Field', name: { kind: 'Name', value: 'description' } },
					{ kind: 'Field', name: { kind: 'Name', value: 'priority' } },
					{ kind: 'Field', name: { kind: 'Name', value: 'reminderAllDay' } },
					{ kind: 'Field', name: { kind: 'Name', value: 'status' } },
					{ kind: 'Field', name: { kind: 'Name', value: 'reminderAt' } },
					{ kind: 'Field', name: { kind: 'Name', value: 'title' } },
					{ kind: 'Field', name: { kind: 'Name', value: 'createdAt' } }
				]
			}
		}
	]
} as unknown as DocumentNode<UpdateTaskMutation, UpdateTaskMutationVariables>;
export const UpdateTaskStatusDocument = {
	kind: 'Document',
	definitions: [
		{
			kind: 'OperationDefinition',
			operation: 'mutation',
			name: { kind: 'Name', value: 'updateTaskStatus' },
			variableDefinitions: [
				{
					kind: 'VariableDefinition',
					variable: { kind: 'Variable', name: { kind: 'Name', value: 'id' } },
					type: {
						kind: 'NonNullType',
						type: { kind: 'NamedType', name: { kind: 'Name', value: 'ID' } }
					}
				},
				{
					kind: 'VariableDefinition',
					variable: { kind: 'Variable', name: { kind: 'Name', value: 'status' } },
					type: {
						kind: 'NonNullType',
						type: { kind: 'NamedType', name: { kind: 'Name', value: 'Status' } }
					}
				}
			],
			selectionSet: {
				kind: 'SelectionSet',
				selections: [
					{
						kind: 'Field',
						name: { kind: 'Name', value: 'updateTask' },
						arguments: [
							{
								kind: 'Argument',
								name: { kind: 'Name', value: 'updateTask' },
								value: {
									kind: 'ObjectValue',
									fields: [
										{
											kind: 'ObjectField',
											name: { kind: 'Name', value: 'id' },
											value: { kind: 'Variable', name: { kind: 'Name', value: 'id' } }
										},
										{
											kind: 'ObjectField',
											name: { kind: 'Name', value: 'status' },
											value: { kind: 'Variable', name: { kind: 'Name', value: 'status' } }
										}
									]
								}
							}
						],
						selectionSet: {
							kind: 'SelectionSet',
							selections: [
								{ kind: 'Field', name: { kind: 'Name', value: 'id' } },
								{ kind: 'Field', name: { kind: 'Name', value: 'status' } }
							]
						}
					}
				]
			}
		}
	]
} as unknown as DocumentNode<UpdateTaskStatusMutation, UpdateTaskStatusMutationVariables>;
export const FindTasksDocument = {
	kind: 'Document',
	definitions: [
		{
			kind: 'OperationDefinition',
			operation: 'query',
			name: { kind: 'Name', value: 'findTasks' },
			variableDefinitions: [
				{
					kind: 'VariableDefinition',
					variable: { kind: 'Variable', name: { kind: 'Name', value: 'priority' } },
					type: { kind: 'NamedType', name: { kind: 'Name', value: 'Priority' } }
				},
				{
					kind: 'VariableDefinition',
					variable: { kind: 'Variable', name: { kind: 'Name', value: 'status' } },
					type: { kind: 'NamedType', name: { kind: 'Name', value: 'Status' } }
				}
			],
			selectionSet: {
				kind: 'SelectionSet',
				selections: [
					{
						kind: 'Field',
						name: { kind: 'Name', value: 'findTasks' },
						arguments: [
							{
								kind: 'Argument',
								name: { kind: 'Name', value: 'priority' },
								value: { kind: 'Variable', name: { kind: 'Name', value: 'priority' } }
							},
							{
								kind: 'Argument',
								name: { kind: 'Name', value: 'status' },
								value: { kind: 'Variable', name: { kind: 'Name', value: 'status' } }
							}
						],
						selectionSet: {
							kind: 'SelectionSet',
							selections: [
								{ kind: 'Field', name: { kind: 'Name', value: 'id' } },
								{ kind: 'Field', name: { kind: 'Name', value: 'priority' } },
								{ kind: 'Field', name: { kind: 'Name', value: 'createdAt' } },
								{ kind: 'Field', name: { kind: 'Name', value: 'reminderAllDay' } },
								{ kind: 'Field', name: { kind: 'Name', value: 'status' } },
								{ kind: 'Field', name: { kind: 'Name', value: 'reminderAt' } },
								{ kind: 'Field', name: { kind: 'Name', value: 'title' } }
							]
						}
					}
				]
			}
		}
	]
} as unknown as DocumentNode<FindTasksQuery, FindTasksQueryVariables>;
export const GetTaskDocument = {
	kind: 'Document',
	definitions: [
		{
			kind: 'OperationDefinition',
			operation: 'query',
			name: { kind: 'Name', value: 'getTask' },
			variableDefinitions: [
				{
					kind: 'VariableDefinition',
					variable: { kind: 'Variable', name: { kind: 'Name', value: 'taskId' } },
					type: {
						kind: 'NonNullType',
						type: { kind: 'NamedType', name: { kind: 'Name', value: 'ID' } }
					}
				}
			],
			selectionSet: {
				kind: 'SelectionSet',
				selections: [
					{
						kind: 'Field',
						name: { kind: 'Name', value: 'getTask' },
						arguments: [
							{
								kind: 'Argument',
								name: { kind: 'Name', value: 'taskId' },
								value: { kind: 'Variable', name: { kind: 'Name', value: 'taskId' } }
							}
						],
						selectionSet: {
							kind: 'SelectionSet',
							selections: [
								{ kind: 'Field', name: { kind: 'Name', value: 'id' } },
								{ kind: 'Field', name: { kind: 'Name', value: 'priority' } },
								{ kind: 'Field', name: { kind: 'Name', value: 'createdAt' } },
								{ kind: 'Field', name: { kind: 'Name', value: 'description' } },
								{ kind: 'Field', name: { kind: 'Name', value: 'reminderAllDay' } },
								{ kind: 'Field', name: { kind: 'Name', value: 'status' } },
								{ kind: 'Field', name: { kind: 'Name', value: 'reminderAt' } },
								{ kind: 'Field', name: { kind: 'Name', value: 'title' } }
							]
						}
					}
				]
			}
		}
	]
} as unknown as DocumentNode<GetTaskQuery, GetTaskQueryVariables>;
