/*
 * SPDX-FileCopyrightText: 2026 Zextras <https://www.zextras.com>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */
/* eslint-disable camelcase,no-shadow */
// THIS FILE IS AUTOGENERATED BY GRAPHQL-CODEGEN. DO NOT EDIT!
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
	ID: { input: string; output: string };
	String: { input: string; output: string };
	Boolean: { input: boolean; output: boolean };
	Int: { input: number; output: number };
	Float: { input: number; output: number };
	DateTime: { input: number; output: number };
};

export type Config = {
	__typename?: 'Config';
	name: Scalars['String']['output'];
	value: Scalars['String']['output'];
};

export type Mutation = {
	__typename?: 'Mutation';
	createTask?: Maybe<Task>;
	trashTask?: Maybe<Scalars['ID']['output']>;
	updateTask?: Maybe<Task>;
};

export type MutationCreateTaskArgs = {
	newTask: NewTaskInput;
};

export type MutationTrashTaskArgs = {
	taskId: Scalars['ID']['input'];
};

export type MutationUpdateTaskArgs = {
	updateTask: UpdateTaskInput;
};

export type NewTaskInput = {
	description?: InputMaybe<Scalars['String']['input']>;
	priority?: InputMaybe<Priority>;
	reminderAllDay?: InputMaybe<Scalars['Boolean']['input']>;
	reminderAt?: InputMaybe<Scalars['DateTime']['input']>;
	status?: InputMaybe<Status>;
	title: Scalars['String']['input'];
};

export enum Priority {
	High = 'HIGH',
	Low = 'LOW',
	Medium = 'MEDIUM'
}

export type Query = {
	__typename?: 'Query';
	findTasks: Array<Maybe<Task>>;
	getServiceInfo: ServiceInfo;
	getTask?: Maybe<Task>;
};

export type QueryFindTasksArgs = {
	priority?: InputMaybe<Priority>;
	status?: InputMaybe<Status>;
};

export type QueryGetTaskArgs = {
	taskId: Scalars['ID']['input'];
};

export type ServiceInfo = {
	__typename?: 'ServiceInfo';
	flavour: Scalars['String']['output'];
	name: Scalars['String']['output'];
	version: Scalars['String']['output'];
};

export enum Status {
	Complete = 'COMPLETE',
	Open = 'OPEN'
}

export type Task = {
	__typename?: 'Task';
	createdAt: Scalars['DateTime']['output'];
	description?: Maybe<Scalars['String']['output']>;
	id: Scalars['ID']['output'];
	priority: Priority;
	reminderAllDay?: Maybe<Scalars['Boolean']['output']>;
	reminderAt?: Maybe<Scalars['DateTime']['output']>;
	status: Status;
	title: Scalars['String']['output'];
};

export type UpdateTaskInput = {
	description?: InputMaybe<Scalars['String']['input']>;
	id: Scalars['ID']['input'];
	priority?: InputMaybe<Priority>;
	reminderAllDay?: InputMaybe<Scalars['Boolean']['input']>;
	reminderAt?: InputMaybe<Scalars['DateTime']['input']>;
	status?: InputMaybe<Status>;
	title?: InputMaybe<Scalars['String']['input']>;
};

export * from './operations';
