/*
 * SPDX-FileCopyrightText: 2023 Zextras <https://www.zextras.com>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import type { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
	overwrite: true,
	schema: {
		'https://sw-demo.zextras.io/services/tasks/graphql/': {
			headers: {
				Cookie:
					'ZM_AUTH_TOKEN=0_f66e2fd8fb4558d7fc42bf239a7c68d32fc273c7_69643d33363a63333235353234352d666261362d343230632d616633322d6263303364393934616439333b6578703d31333a313637373037363335383831373b747970653d363a7a696d6272613b753d313a613b7469643d31303a313634303632363639313b637372663d313a313b'
			}
		}
	},
	generates: {
		'src/gql/schema.graphql': {
			plugins: [
				// https://the-guild.dev/graphql/codegen/plugins/other/schema-ast
				'schema-ast',
				// https://the-guild.dev/graphql/codegen/plugins/other/add
				{
					add: {
						content: ['" THIS FILE IS AUTOGENERATED BY GRAPHQL-CODEGEN. DO NOT EDIT! "']
					}
				}
			]
		},
		'src/gql/types.ts': {
			documents: ['src/**/*.graphql'],
			plugins: [
				// https://the-guild.dev/graphql/codegen/plugins/typescript/typescript
				'typescript',
				// https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-operations
				'typescript-operations',
				// https://the-guild.dev/graphql/codegen/plugins/typescript/typed-document-node
				'typed-document-node',
				// https://the-guild.dev/graphql/codegen/plugins/other/add
				{
					add: {
						content: [
							'/* eslint-disable camelcase,no-shadow */',
							'// THIS FILE IS AUTOGENERATED BY GRAPHQL-CODEGEN. DO NOT EDIT!'
						]
					}
				}
			],
			config: {
				defaultScalarType: 'unknown',
				exportFragmentSpreadSubTypes: true,
				mergeFragmentTypes: true,
				nonOptionalTypename: false,
				scalars: {
					DateTime: 'number'
				},
				strictScalars: true
			}
		},
		'src/gql/possible-types.ts': {
			documents: ['src/**/*.graphql'],
			plugins: [
				'fragment-matcher',
				{ add: { content: '// THIS FILE IS AUTOGENERATED BY GRAPHQL-CODEGEN. DO NOT EDIT!' } }
			]
		}
	},
	hooks: {
		afterAllFileWrite:
			'eslint --fix --resolve-plugins-relative-to node_modules/@zextras/carbonio-ui-configs src'
	}
};

export default config;
