/*
 * SPDX-FileCopyrightText: 2023 Zextras <https://www.zextras.com>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import type { CodegenConfig } from '@graphql-codegen/cli';
import type { TypeScriptTypedDocumentNodesConfig } from '@graphql-codegen/typed-document-node';
import type { TypeScriptPluginConfig } from '@graphql-codegen/typescript';
import type { TypeScriptDocumentsPluginConfig } from '@graphql-codegen/typescript-operations';

const config: CodegenConfig = {
	overwrite: true,
	// The upstream schema (carbonio-tasks-ce) is currently not loadable by codegen: it references
	// an undeclared `BigInteger` scalar. Until that is fixed upstream, generate from the committed
	// schema snapshot. To re-sync with the backend, restore the remote URL below:
	// 'https://raw.githubusercontent.com/zextras/carbonio-tasks-ce/devel/app/docs/schema.graphql'
	schema: 'src/gql/schema.graphql',
	generates: {
		// Base schema types (object types, enums, inputs, Scalars). In v6 the typescript-operations
		// plugin is self-contained and would re-emit Input/Enum types, so the two plugins can no
		// longer share a single file. Keep the typescript plugin as the single source of schema
		// types here and re-export the operation types so existing `gql/types` imports keep working.
		'src/gql/types.ts': {
			plugins: [
				// https://the-guild.dev/graphql/codegen/plugins/typescript/typescript
				'typescript',
				// https://the-guild.dev/graphql/codegen/plugins/other/add
				{
					add: {
						content: [
							'/* eslint-disable camelcase,no-shadow */',
							'// THIS FILE IS AUTOGENERATED BY GRAPHQL-CODEGEN. DO NOT EDIT!'
						]
					}
				},
				{ add: { placement: 'append', content: "export * from './operations';" } }
			],
			config: {
				defaultScalarType: 'unknown',
				nonOptionalTypename: false,
				scalars: {
					DateTime: 'number'
				},
				strictScalars: true,
				useTypeImports: true
			} satisfies TypeScriptPluginConfig
		},
		// Operation types (variables, results, fragments) and TypedDocumentNodes. Schema types are
		// imported from ./types instead of being re-declared, avoiding duplicate identifiers.
		'src/gql/operations.ts': {
			documents: ['src/**/*.graphql'],
			plugins: [
				// https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-operations
				'typescript-operations',
				// https://the-guild.dev/graphql/codegen/plugins/typescript/typed-document-node
				'typed-document-node',
				// https://the-guild.dev/graphql/codegen/plugins/other/add
				{
					add: {
						content: [
							'/* eslint-disable camelcase,no-shadow */',
							'// THIS FILE IS AUTOGENERATED BY GRAPHQL-CODEGEN. DO NOT EDIT!'
						]
					}
				}
			],
			config: {
				defaultScalarType: 'unknown',
				exportFragmentSpreadSubTypes: true,
				// Relative to this config file's location: points at src/gql/types.ts, which holds the
				// schema types. Operation types import them from there instead of re-declaring them.
				importSchemaTypesFrom: 'src/gql/types',
				mergeFragmentTypes: true,
				nonOptionalTypename: false,
				scalars: {
					DateTime: 'number',
					// v6 typescript-operations emits ID input as `string | number` natively; pin it to
					// `string` to match how IDs are used across the app (and the v5 behaviour).
					ID: { input: 'string', output: 'string' }
				},
				strictScalars: true,
				useTypeImports: true
			} satisfies TypeScriptDocumentsPluginConfig &
				TypeScriptTypedDocumentNodesConfig & { importSchemaTypesFrom?: string }
		},
		'src/gql/possible-types.ts': {
			documents: ['src/**/*.graphql'],
			plugins: [
				'fragment-matcher',
				{ add: { content: '// THIS FILE IS AUTOGENERATED BY GRAPHQL-CODEGEN. DO NOT EDIT!' } }
			]
		}
	},
	hooks: {
		afterAllFileWrite:
			'eslint --fix --resolve-plugins-relative-to node_modules/@zextras/carbonio-ui-configs'
	}
};

export default config;
